### ISSUE TITLE
Render progress bar disappears after loading a scene.

### ISSUE THREAD

**Issue by ThatRedox** [leMaik/chunky-launcher-standalone#8]
Simply loading a scene causes the render progress bar to disappear. This only appears to happen with some scenes. There are no errors/warnings/logs in the console.
Happens with both 2.4.0 snapshots and 2.3.0

**Comment by leMaik** [comment]
Is this related to the Chunky standalone launcher or a bug in Chunky?

**Comment by ThatRedox** [comment]
I'm not sure (and can't test at the moment). It is either a java 16 issue or a standalone issue. My java 8 installation does not have this issue.

**Comment by leMaik** [comment]
Seems like this was fixed by https://github.com/chunky-dev/chunky/pull/1021
